# Generated by Django 2.2.4 on 2019-08-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190817_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goingout',
            name='name',
        ),
        migrations.AddField(
            model_name='goingout',
            name='organisator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organisedGoingOuts', to='application.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goingout',
            name='participants',
            field=models.ManyToManyField(related_name='goingOuts', to='application.User'),
        ),
    ]
