# Generated by Django 2.2.4 on 2019-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190818_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='visited',
            field=models.ManyToManyField(related_name='visitors', to='application.EscapeRoom'),
        ),
    ]
