# Generated by Django 2.2.4 on 2019-09-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_user_buddies'),
    ]

    operations = [
        migrations.AddField(
            model_name='escaperoom',
            name='url',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
